export const arrData = [
  {
    title: "Saved audio 1",
    fileName: "saved-audio-1.file",
    length: 13,
    timeStamp: "13-02-24-timecode",
    id: 1,
  },
  {
    title: "Positive Affirmations",
    fileName: "positive-affirmations.file",
    length: 13,
    timeStamp: "13-02-24-timecode",
    id: 2,
  },
  {
    title: "Saved audio 2",
    fileName: "saved-audio-2.file",
    length: 13,
    timeStamp: "13-02-24-timecode",
    id: 3,
  },
  {
    title: "Hopes and Desires",
    fileName: "hopes-and-desires.file",
    length: 13,
    timeStamp: "13-02-24-timecode",
    id: 4,
  },
  {
    title: "this and that",
    fileName: "this-and-that.file",
    length: 13,
    timeStamp: "13-02-24-timecode",
    id: 5,
  },
  {
    title: "Here and There",
    fileName: "Here-and-There.file",
    length: 13,
    timeStamp: "13-02-24-timecode",
    id: 6,
  },
  {
    title: "Hot and Cold",
    fileName: "Hot-and-Cold.file",
    length: 13,
    timeStamp: "13-02-24-timecode",
    id: 7,
  },
  {
    title: "Yes and No",
    fileName: "Yes-and-No.file",
    length: 13,
    timeStamp: "13-02-24-timecode",
    id: 8,
  },
  {
    title: "In and Out",
    fileName: "In-and-Out.file",
    length: 13,
    timeStamp: "13-02-24-timecode",
    id: 9,
  },
];
